serenity.project.name=Reto Tecnico Demo Web Shop
webdriver.driver=chrome
webdriver.base.url=https://demowebshop.tricentis.com/
serenity.take.screenshots=AFTER_EACH_STEP
serenity.console.colors=true
chrome.switches=--remote-allow-origins=*,--disable-notifications,--disable-save-password-bubble,--disable-features=PasswordCheck,PasswordManagerOnboarding,AutofillServerCommunication
chrome_preferences.profile.password_manager_enabled=false
chrome_preferences.credentials_enable_service=false
chrome_preferences.profile.password_manager_leak_detection=false
chrome_preferences.autofill.profile_enabled=false
chrome_preferences.autofill.credit_card_enabled=false
chrome_preferences.safebrowsing.enabled=false
chrome_preferences.safebrowsing.password_protection_enabled=false
